version: '3'

services:
  nginx:
    image: nginx:alpine
    links:
      - swoole
    ports:
      - 34332:8080
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./core/chat.html:/usr/share/nginx/html/index.html
  swoole:
    image: phpswoole/swoole:4.4.15-php7.2
    ports:
      - 9502:9502
    volumes:
      - ./core:/var/www